### ISSUE TITLE
センサーの起算点の計算方法を考える

### ISSUE THREAD

**Issue by YoshidaF** [yamamonsatoshi/lab#6]
# title1
## title2

- センサの起算点を考える
    - 立ち上がりが遅い
    - どのようにして計算するか。
- センサの起算点を考える

---

**Comment by yamamonsatoshi** [comment]
## 手法の候補
- 過去平均値に基づく特定の帯域を計算し、それを逸脱した地点を起算点とする
   - リアルタイムでの起算点の検出が可能
- 曲線にフィッティング
   - fittingの関数が複雑になる？？
   - 基本的に結果が得られたのちの分析にしか適さない
   - これをするなら、2つの近接した座標で直線を描いてタイムスタンプの値を出しても良いくらいな気がしている。

## 留意点
- センサの起算点のみならず、応答時間(https://www.optex-fa.jp/tech_guide/dsp_guide/)的な漸増する期間の指標も出す必要がある。

**Comment by yamamonsatoshi** [comment]
## 実験中に使用する場合と事後分析で分けることも可能なので、ほとんど論点とならない。
- 実験中は平均値とSDでのバンドを設けて、それの内部か判断することによってセンサのon/offを判断する。
- 事後的にはfittingも可能だが、上の分析があれば不要となるかも。
    - ただし、応答時間は出した方が良いので、fittingは行う方が良い。

後で考えれば良いので、今はclose
